title: Hi, I'm Dylan
description: > # this means to ignore newlines until "baseurl:"
  Dylan Blough data science data scientist
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: http://dylanblough.github.io # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dylan Blough # add your name
author-img: DylanBlough_headshot_250w.jpg # add your photo
about-author: I am a data scientist based in DC, always on the look out for new projects. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: DylanBlough # add your Github handle
social-linkedin: https://www.linkedin.com/in/dylan-blough-b2185619a/  # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
